In [ ]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
dataset = pd.read_csv('play_tennis.csv')

In [ ]:
dataset.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [ ]:
#  Problem 1: outlook = Sunny, 	temp = Hot,	humidity = High, wind = Weak  , Play or no Play

# P(Yes/ Sunny, Hot, High, Weak) = P(Sunny/ Yes)* P(Hot/Yes), * P(High/Yes), P(Weak/Yes) * P(Yes)


# P(No/ Sunny, Hot, High, Weak) = P(Sunny/ No)* P(Hot/No), * P(High/No), P(Weak/No) * P(No)

# compare and decide to choose maximum posteriori rule

In [ ]:
# Training

# In naive bias, it creates look up tables for all the needed probability values by going through the dataset.
# and store it in look up table

# Testing
# as it has already all prob available, if we give any new point it goes checks the values and give us the prediction.


# Lookup_table (Dictationary)

In [ ]:
#  we will calculate look_up table

# P(Yes)
# P(No)

In [ ]:
dataset['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [ ]:
py = 9/14
pn = 5/14

In [ ]:
py, pn

(0.6428571428571429, 0.35714285714285715)

In [ ]:
pd.crosstab(dataset['outlook'], dataset['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [ ]:
pon = 0
prn = 2/5
psn = 3/5

poy = 4/9
pry = 3/9
psy = 2/9

In [ ]:
pd.crosstab(dataset['temp'], dataset['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [ ]:
pCoolNo = 1/5
pHotNo = 2/5
pMildNo = 2/5

pCoolYes = 3/9
pHotYes = 2/9
pMildYes = 4/9

In [ ]:
pd.crosstab(dataset['humidity'], dataset['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [ ]:
pHighNo = 4/5
pNormalNo = 1/5

pHighYes = 3/9
pNormalYes = 6/9

In [ ]:
pd.crosstab(dataset['wind'], dataset['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [ ]:
pStrongNo = 3/5
pWeakNo = 2/5

pStrongYes = 3/9
pWeakYes = 6/9

In [ ]:
# outlook = Sunny, 	temp = Hot,	humidity = High, wind = Weak  , Play or no Play

Pyes = py*psy*pHotYes*pHighYes*pWeakYes
Pno = pn*prn*pHotNo*pHighNo*pWeakNo

In [ ]:
Pyes, Pno

(0.007054673721340388, 0.01828571428571429)

In [ ]:
# result will be No play